### ISSUE TITLE
photo.jpg is not displayed by IE 11

### ISSUE THREAD

**Issue by wintermeyer** [amooma/www.amooma.de#12]
The file `photo.jpg` doesn't get displayed in IE 11 on Windows 8.1. Maybe it is something easy to fix. If not: Please feel free to close this one without fixing it. IE users are a tiny minority of our users.
![bildschirmfoto 2015-01-25 um 17 38 07](https://cloud.githubusercontent.com/assets/69770/5892276/2b6c665e-a4b9-11e4-897f-e4a3e60ad07a.png)

**Comment by wintermeyer** [comment]
Fun fact: IE 10 and 9 on Windows 7 work. 
![bildschirmfoto 2015-01-25 um 17 42 20](https://cloud.githubusercontent.com/assets/69770/5892285/9e893cc0-a4b9-11e4-8360-a6422ef68bf9.png)

**Comment by KasperTidemann** [comment]
This should be fixed now by the latest commit coming up. This is from Internet Explorer 11 on Windows 8.1 (on a Surface):

![denhffi](https://cloud.githubusercontent.com/assets/498350/6046984/17001b66-aca7-11e4-98b2-f1c4bb97157c.png)
